import { PortfolioConfig, Transaction, MicroSpendingLimit } from '../types';

export const DEFAULT_SALARY = 3000000;

export const INITIAL_PORTFOLIO: PortfolioConfig = {
  salary: DEFAULT_SALARY,
  totalPercent: 100,
  lastUpdated: new Date().toISOString(),
  isConfirmed: true,
  categories: [
    {
      id: 'living',
      name: '생활비',
      percent: 50,
      amount: 1500000,
      color: '#EF4444',
      bgColor: '#FEE2E2',
      iconName: 'home',
      description: '주거비, 식비, 공과금, 교통비 등 필수 생활 지출',
    },
    {
      id: 'saving',
      name: '저축',
      percent: 30,
      amount: 900000,
      color: '#10B981',
      bgColor: '#D1FAE5',
      iconName: 'savings',
      description: '비상금 통장, 정기 적금, 청약 등 미래 자산',
    },
    {
      id: 'investment',
      name: '투자',
      percent: 15,
      amount: 450000,
      color: '#6366F1',
      bgColor: '#E0E7FF',
      iconName: 'trending_up',
      description: '국내/해외 주식, ETF, 연금저축, 펀드 등',
    },
    {
      id: 'etc',
      name: '기타',
      percent: 5,
      amount: 150000,
      color: '#64748B',
      bgColor: '#F1F5F9',
      iconName: 'more_horiz',
      description: '경조사비, 자기계발, 비정기 지출 등',
    },
  ],
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    merchant: '맛있는 식당',
    category: '식비',
    amount: 35000,
    date: '오늘',
    time: '12:30',
    memo: '점심 식사 (동료들과 삼계탕)',
    isMicroSpending: false,
  },
  {
    id: 'tx-2',
    merchant: '패션 백화점',
    category: '쇼핑',
    amount: 120000,
    date: '어제',
    time: '15:45',
    memo: '여름 린넨 셔츠 구매',
    isMicroSpending: false,
  },
  {
    id: 'tx-3',
    merchant: '지하철 요금',
    category: '교통',
    amount: 1500,
    date: '3일 전',
    time: '08:45',
    memo: '출근 지하철 결제',
    isMicroSpending: true,
  },
  {
    id: 'tx-4',
    merchant: '카페',
    category: '식비',
    amount: 4500,
    date: '3일 전',
    time: '14:20',
    memo: '아이스 아메리카노 테이크아웃',
    isMicroSpending: true,
  },
  {
    id: 'tx-5',
    merchant: '쿠팡',
    category: '쇼핑',
    amount: 14500,
    date: '4일 전',
    time: '23:10',
    memo: '생수 및 생활용품 로켓배송',
    isMicroSpending: true,
  },
  {
    id: 'tx-6',
    merchant: '다이소',
    category: '쇼핑',
    amount: 8000,
    date: '5일 전',
    time: '18:15',
    memo: '수납 바구니 & 건전지',
    isMicroSpending: true,
  },
  {
    id: 'tx-7',
    merchant: '스타벅스',
    category: '식비',
    amount: 6300,
    date: '6일 전',
    time: '09:00',
    memo: '바닐라 라떼',
    isMicroSpending: true,
  },
  {
    id: 'tx-8',
    merchant: 'CGV 영화관',
    category: '문화/여가',
    amount: 15000,
    date: '1주일 전',
    time: '19:30',
    memo: '주말 영화 관람',
    isMicroSpending: true,
  },
  {
    id: 'tx-9',
    merchant: '편의점 GS25',
    category: '기타',
    amount: 4200,
    date: '1주일 전',
    time: '22:40',
    memo: '야식 컵라면 & 음료',
    isMicroSpending: true,
  },
  {
    id: 'tx-10',
    merchant: '올리브영',
    category: '쇼핑',
    amount: 18900,
    date: '8일 전',
    time: '16:00',
    memo: '클렌징 폼 구매',
    isMicroSpending: true,
  },
];

export const INITIAL_MICRO_LIMIT: MicroSpendingLimit = {
  monthlyLimit: 300000,
  currentUsed: 240000,
  lastMonthUsed: 208700,
  percentIncrease: 15,
  warningThreshold: 80,
};

export const INITIAL_MERCHANT_PATTERNS = [
  {
    id: 'p-1',
    merchant: '쿠팡',
    count: 12,
    totalAmount: 114500,
    category: '쇼핑/이커머스',
    iconName: 'shopping_bag',
    badgeBg: 'bg-[#EDE9FE]',
    badgeColor: 'text-[#6D28D9]',
    tag: '12회 결제',
  },
  {
    id: 'p-2',
    merchant: '다이소',
    count: 8,
    totalAmount: 45000,
    category: '생활잡화',
    iconName: 'store',
    badgeBg: 'bg-[#E0E7FF]',
    badgeColor: 'text-[#4338CA]',
    tag: '8회 결제',
  },
  {
    id: 'p-3',
    merchant: '스타벅스',
    count: 6,
    totalAmount: 31200,
    category: '카페/음료',
    iconName: 'coffee',
    badgeBg: 'bg-[#D1FAE5]',
    badgeColor: 'text-[#047857]',
    tag: '6회 결제',
  },
  {
    id: 'p-4',
    merchant: '교통카드',
    count: 32,
    totalAmount: 49300,
    category: '교통',
    iconName: 'directions_subway',
    badgeBg: 'bg-[#E2E8F0]',
    badgeColor: 'text-[#334155]',
    tag: '다수',
  },
];

export const CATEGORY_COLORS: Record<string, { color: string; bg: string }> = {
  '식비': { color: '#10B981', bg: '#D1FAE5' },
  '쇼핑': { color: '#F59E0B', bg: '#FEF3C7' },
  '교통': { color: '#3B82F6', bg: '#DBEAFE' },
  '문화/여가': { color: '#8B5CF6', bg: '#EDE9FE' },
  '기타': { color: '#EF4444', bg: '#FEE2E2' },
  '카페/간식': { color: '#10B981', bg: '#D1FAE5' },
  '생활잡화': { color: '#6366F1', bg: '#E0E7FF' },
};
